Migrate to MSK
Financial-Times/upp-next-video-content-collection-mapper pull request #26
Opened 2022-08-18 16:08 UTC by elenasuteva

# Description

## What

As part of the kafka migration, this PR contains the changes for migrating from old kafka to MSK.

Using the Kafka-client-go/v3 library replaced the consumer and producer of Kafka messages, updated env vars.
Start producer and soncumer in the main function, update logger to v2 and update go version to 18.
Kafka consumer lag monitor healthcheck added.
Remove unused functions and tests are fixed.

## Why

https://financialtimes.atlassian.net/browse/UPPSF-3415

## Anything, in particular, you'd like to highlight to reviewers

Mention here sections of code which you would like reviewers to pay extra attention to .E.g

## Scope and particulars of this PR (Please tick all that apply)

- [ ] Tech hygiene (dependency updating & other tech debt)
- [ ] Bug fix
- [x] Feature
- [ ] Documentation
- [ ] Breaking change
- [ ] Minor change (e.g. fixing a typo, adding config)

___
This Pull Request follows the rules described in our [Pull Requests Guide](https://github.com/Financial-Times/upp-docs/tree/master/guides/pr-guide)

2022-08-19 08:55 UTC, atanasdinov requested changes

2022-08-19 08:55 UTC, atanasdinov commented on README.md
>          --queue-addresses="http://%H:8080"                              Queue address ($Q_ADDR)
Can we also update this to Kafka's port (9092)?

2022-08-19 08:55 UTC, atanasdinov commented on healthcheck.go
> +		Severity:         2,
I'd suggest to set the severity to `3` i.e. `low`.

2022-08-19 08:55 UTC, atanasdinov commented on healthcheck.go
> +	return "OK", err
```suggestion
	return "OK", nil
```

2022-08-19 08:55 UTC, atanasdinov commented on helm/upp-next-video-content-collection-mapper/templates/deployment.yaml
> -        - name: Q_READ_TOPIC
How is this working? We can't stop reading from `NativeCmsPublicationEvents`?

2022-08-19 08:55 UTC, atanasdinov commented on helm/upp-next-video-content-collection-mapper/app-configs/upp-next-video-content-collection-mapper_eks_delivery.yaml
> -  Q_READ_TOPIC: NativeCmsPublicationEvents
We can't be removing this.

2022-08-19 08:55 UTC, atanasdinov commented on helm/upp-next-video-content-collection-mapper/app-configs/upp-next-video-content-collection-mapper_eks_delivery.yaml
>    Q_GROUP: NextVideoContentCollectionMapper
Could we set this to `upp-next-video-content-collection-mapper` for consistency purposes?

2022-08-19 08:55 UTC, atanasdinov commented on main.go
> +				log.WithError(err).Error("Producer could not stop")
```suggestion
				log.WithError(err).Error("Consumer could not stop")
```

2022-08-19 10:42 UTC, elenasuteva commented on healthcheck.go
> +		Severity:         2,
And how do we determine the severity of the healthchecks in general?

2022-08-19 11:25 UTC, elenasuteva commented on helm/upp-next-video-content-collection-mapper/app-configs/upp-next-video-content-collection-mapper_eks_delivery.yaml
> -  Q_READ_TOPIC: NativeCmsPublicationEvents
Done by mistake, reverting

2022-08-19 12:18 UTC, atanasdinov commented on healthcheck.go
> +		Severity:         2,
Depends on their importance. The lag monitoring is a status check which, when triggered, would either show us that there's a problem with the consumer connection or that there's an increase in the traffic to the cluster (which in itself is not an issue generally).

2022-08-19 13:36 UTC, elenasuteva commented on healthcheck.go
> +		Severity:         2,
Thank you!

2022-08-19 15:28 UTC, ilian2233 requested changes

2022-08-19 15:28 UTC, ilian2233 commented on main.go
> +		go func(producer *kafka.Producer) {
**issue:** The producer and consumer should be closed after `waitForSignal()` receives a signal. 
```suggestion
		defer go func(producer *kafka.Producer) {
```

2022-08-19 16:58 UTC, elenasuteva commented on main.go
> +		go func(producer *kafka.Producer) {
Thank you, seems like I made a typo here.

2022-08-22 08:00 UTC, atanasdinov reviewed
LGTM! Happy to approve once this minor documentation comment is addressed.

2022-08-22 08:00 UTC, atanasdinov commented on README.md
> +        --queue-kafkaAddress="http://%H:9092"                              Queue address ($Q_ADDR)
```suggestion
        --queue-kafkaAddress="%H:9092"                              Queue address ($Q_ADDR)
```

Please also check whether the description is properly formatted (aligned to the right).

2022-08-25 12:24 UTC, atanasdinov approved these changes

2022-08-25 15:55 UTC, elenasuteva commented
@atanasdinov should I decrease the replicaCount from 2 to 1?

2022-08-25 16:08 UTC, ilian2233 approved these changes

2022-08-25 16:13 UTC, atanasdinov commented
> @atanasdinov should I decrease the replicaCount from 2 to 1?

Yes, it'd be better.

2022-08-26 12:37 UTC, atanasdinov approved these changes

2022-08-26 13:58 UTC, merged